interface hypermap-explorer {
    type namehash = string;
    type name = string;

    variant request {
        /// prints a tree from the given name in terminal
        /// blob: none
        tree(name),
        /// prints a tree from the given namehash in terminal
        /// blob: none
        tree-from-namehash(namehash),
    }
}

world hypermap-explorer-nick-dot-hypr-v0 {
    import hypermap-explorer;
    include process-v1;
}
